[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "wavslm"
version = "0.0.1"
description = "Single-stream speech language modeling via WavLM distillation"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
    { name = "Luca Della Libera", email = "luca.dellalib@gmail.com" },
]
keywords = [
    "audio generation",
    "FocalCodec",
    "PyTorch",
    "speech generation",
    "speech language modeling",
    "speech processing",
    "speech synthesis",
    "WavLM",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: GPU :: NVIDIA CUDA",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "huggingface-hub",
    "safetensors",
    "torch",
]

[project.urls]
Homepage = "https://lucadellalib.github.io/wavslm-web/"
Paper = "https://arxiv.org/abs/2603.05299"
Repository = "https://github.com/lucadellalib/wavslm"

[tool.setuptools]
py-modules = ["wavslm"]

[dependency-groups]
dev = [
    "pre-commit==4.6.0",
]
